pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python3 main.py'
            }
        }
        stage('Test') {
            steps {
                sh 'echo Executing tests ...'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Deploy to dev ...'
            }
        }
    }
}
