pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python3 main.py'
            }
        }
        stage('Test') {
            steps {
                sh 'echo Executing tests ...'
            }
        }
        stage('SendToArtifactory') {
            steps {
                sh 'Sending pop-liabilities:$(cat versions) to artifactory ...'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Deploy pop-liabilities:$(cat versions) to dev ...'
            }
        }
    }
}
